name: CI
on: [push]
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  build-vuetify:
    name: Build vuetify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/yarn-install
      - run: yarn build vuetify
      - uses: ./.github/actions/upload-artifact
        with:
          name: vuetify-dist
          path: >
            packages/vuetify/dist
            packages/vuetify/lib

  lint:
    name: Lint
    needs: [build-vuetify]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/download-artifact
        with:
          name: vuetify-dist
      - uses: ./.github/actions/yarn-install
      - run: yarn lerna run lint --scope @fabriq/vuetify-compat --scope @vuetify/api-generator

  test-jest:
    name: Test (Jest)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/yarn-install
      - run: yarn run test:coverage -i
        working-directory: ./packages/vuetify

  test-cypress:
    name: Test (Cypress)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/yarn-install
      - run: yarn cy:run
        if: ${{ !startswith(github.ref, 'refs/tags/v') }}
        working-directory: ./packages/vuetify
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: ./packages/vuetify/cypress/screenshots/
          if-no-files-found: ignore
